language: python
python:
  - "2.7"
before_script:
  - 'gem install sass --version "=3.2.12"'
  - 'gem install compass --version "=0.12.2"'
install:
  - python setup.py install
script:
  - python setup.py test
